from pathlib import Path

# ---------- src/agent.ts ----------
p = Path('src/agent.ts')
s = p.read_text()
old = '''const PLACED_ORDER_CHANGE = /\\b(?:change|modify|cancel|update|edit|replace)\\b/i;\n'''
new = '''const PLACED_ORDER_CHANGE = /\\b(?:change|modify|cancel|update|edit|replace)\\b/i;\nconst EXPLICIT_PLACED_ORDER_TARGET = /\\b(?:order\\s*#\\s*\\d+|order\\s+#?\\d+|confirmed\\s+order|placed\\s+order|existing\\s+order)\\b/i;\n\n/** Legacy/model custom alerts that belong to a pending catering request, not a placed order. */\nfunction isCustomWorkAlert(note: string): boolean {\n  if (/^Custom\\/bulk request(?: updated)?:/i.test(note)) return true;\n  const headcount = /\\b\\d{1,3}\\s*(?:people|persons|pax|members|guests)\\b/i.test(note);\n  const customWork = /\\b(?:quote|price|cater(?:ing)?|bulk|custom|tray)\\b/i.test(note);\n  return headcount && customWork;\n}\n\n/** A headcount edit belongs to the active unplaced catering draft unless a real placed order is named. */\nfunction pendingCustomHeadcountChange(text: string, draft: Draft | null): number | null {\n  if (!draft?.custom || !PLACED_ORDER_CHANGE.test(text) || EXPLICIT_PLACED_ORDER_TARGET.test(text)) return null;\n  return customHeadcount(text);\n}\n'''
assert old in s, 'agent constants anchor not found'
s = s.replace(old, new, 1)

anchor = '''    if (draft?.custom && (THANKS.test(text) || CUSTOM_ACK.test(text))) {\n      out.route = "custom_ack";\n      const ready = customQuoteIsCurrent(draft) && !!draft.pickup_local;\n      out.replies.push(ready\n        ? "You're welcome! Your custom order details are ready. Reply CONFIRM THE ORDER when you want me to place it."\n        : "You're welcome! Your custom order request is saved. Annapurna Home Foods will finalize the remaining details here.");\n      for (const reply of out.replies) store.addMessage(msg.from, "agent", reply, this.now());\n      return out;\n    }\n\n'''
insert = anchor + '''    // A change such as "my new catering request, change it to 25 people instead of 20"\n    // must update the pending custom draft, never route to cancel/change a placed order.\n    const changedHeadcount = pendingCustomHeadcountChange(text, draft);\n    if (draft?.custom && changedHeadcount != null) {\n      const hadQuote = draft.custom.price != null;\n      const next: Draft = {\n        ...draft,\n        items: draft.items.map((it) => ({ ...it, qty: changedHeadcount })),\n        readback_hash: null,\n        stage: "collecting",\n        custom: {\n          ...draft.custom,\n          request: text.slice(0, 300),\n          price: null,\n          approved: false,\n          quote_key: null,\n        },\n      };\n      store.putDraft(msg.from, next);\n      // Replace stale custom-work alerts with one current, unlinked request. Never attach this\n      // kind of change to a placed order, which is what creates the dangerous Cancel button.\n      for (const a of store.listAlerts(true)) {\n        if (a.waId === msg.from && a.orderId == null && isCustomWorkAlert(a.note)) store.markAlertDone(a.id);\n      }\n      out.route = "custom_headcount_change";\n      if (hadQuote) out.issues.push("stale_custom_quote");\n      out.replies.push(\n        hadQuote\n          ? `Got it — I updated the pending catering request to ${changedHeadcount} people and cleared the old quoted price. No placed order was changed. Annapurna Home Foods needs to quote the updated request again.`\n          : `Got it — I updated the pending catering request to ${changedHeadcount} people. No placed order was changed. Annapurna Home Foods will confirm the price here.`\n      );\n      await this.raise(\n        msg.from,\n        customer.name || msg.name || "Customer",\n        `Custom/bulk request updated: ${changedHeadcount} people. Needs current price quote. Customer said: "${text.slice(0, 180)}"`,\n        null,\n        out,\n      );\n      for (const reply of out.replies) store.addMessage(msg.from, "agent", reply, this.now());\n      return out;\n    }\n\n'''
assert anchor in s, 'custom ack anchor not found'
s = s.replace(anchor, insert, 1)

old = '''    const ownerNote = typeof raw.owner_note === "string" ? raw.owner_note.trim() : "";\n    if ((raw.needs_owner === true || r.kind === "owner_topic") && !fixes.length) {\n      await this.raise(msg.from, customer.name || msg.name || "Customer", (ownerNote || `Needs Maddy: "${text.slice(0, 140)}"`).slice(0, 300), null, out);\n    }\n'''
new = '''    const ownerNote = typeof raw.owner_note === "string" ? raw.owner_note.trim() : "";\n    if ((raw.needs_owner === true || r.kind === "owner_topic") && !fixes.length) {\n      const baseNote = ownerNote || `Needs Maddy: "${text.slice(0, 140)}"`;\n      // Keep every custom/catering alert recognizable as custom work so fulfillment can close it.\n      const alertNote = custom\n        ? `Custom/bulk request: ${baseNote.replace(/^Custom\\/bulk request:\\s*/i, "")}`\n        : baseNote;\n      await this.raise(msg.from, customer.name || msg.name || "Customer", alertNote.slice(0, 300), null, out);\n    }\n'''
assert old in s, 'owner note anchor not found'
s = s.replace(old, new, 1)

old = '''    for (const a of store.listAlerts(true)) {\n      if (a.waId === waId && a.orderId == null && a.note.startsWith("Custom/bulk request:")) store.markAlertDone(a.id);\n    }\n'''
new = '''    for (const a of store.listAlerts(true)) {\n      if (a.waId === waId && a.orderId == null && isCustomWorkAlert(a.note)) store.markAlertDone(a.id);\n    }\n'''
# replace only the one in placeCustomOrder, but there are earlier same snippets. Use last occurrence.
pos = s.rfind(old)
assert pos >= 0, 'placeCustomOrder alert cleanup anchor not found'
s = s[:pos] + new + s[pos + len(old):]
p.write_text(s)

# ---------- src/store.ts ----------
p = Path('src/store.ts')
s = p.read_text()
anchor = '''  /** Timestamp for owner dashboard metrics that should start fresh with the Vindhu launch. */\n  ownerFreshLaunchAt(): number {\n    const r = this.db.prepare("SELECT json FROM kv WHERE key = ?").get("owner_chat_reset_vindhu_20260927") as Row | undefined;\n    if (!r) return 0;\n    try {\n      const v = JSON.parse(String(r.json)) as { at?: unknown };\n      const n = Number(v.at);\n      return Number.isFinite(n) && n > 0 ? n : 0;\n    } catch {\n      return 0;\n    }\n  }\n\n'''
insert = anchor + '''  /**\n   * True when a customer explicitly deleted their chat. The legacy inference also hides chats\n   * deleted before this marker existed, where later order lifecycle notes reconstructed a fake\n   * status-only thread after the real conversation had been erased.\n   */\n  ownerChatDeleted(waId: string): boolean {\n    const key = `owner_chat_deleted:${waId}`;\n    if (this.db.prepare("SELECT 1 FROM kv WHERE key = ?").get(key)) return true;\n    if (!waId.startsWith("web:")) return false;\n    if (this.db.prepare("SELECT 1 FROM web_sessions WHERE wa_id = ? LIMIT 1").get(waId)) return false;\n    const rows = this.db.prepare("SELECT who, text FROM messages WHERE wa_id = ? ORDER BY id").all(waId) as Row[];\n    const hasOrder = !!this.db.prepare("SELECT 1 FROM orders WHERE wa_id = ? LIMIT 1").get(waId);\n    if (!rows.length) return hasOrder;\n    const lifecycleOnly = rows.every((r) => {\n      if (String(r.who) !== "agent") return false;\n      const text = String(r.text);\n      return /^(?:Annapurna Home Foods confirmed your order #\\d+|Order #\\d+ has been cancelled|Sorry, order #\\d+ has been cancelled|Your order #\\d+ is ready for pickup|Thank you for your order)/i.test(text);\n    });\n    return hasOrder && lifecycleOnly;\n  }\n\n'''
assert anchor in s, 'store ownerFreshLaunchAt anchor not found'
s = s.replace(anchor, insert, 1)

old = '''  addMessage(waId: string, who: Msg["who"], text: string, ts: number): number {\n    const r = this.db.prepare("INSERT INTO messages (wa_id, who, text, ts) VALUES (?, ?, ?, ?)").run(waId, who, text, ts);\n    return Number(r.lastInsertRowid);\n  }\n'''
new = '''  addMessage(waId: string, who: Msg["who"], text: string, ts: number): number {\n    // If a transport ever reuses the same customer id after deletion, a genuine new customer\n    // message starts a new visible thread. System/order lifecycle notes never do this.\n    if (who === "cust") this.db.prepare("DELETE FROM kv WHERE key = ?").run(`owner_chat_deleted:${waId}`);\n    const r = this.db.prepare("INSERT INTO messages (wa_id, who, text, ts) VALUES (?, ?, ?, ?)").run(waId, who, text, ts);\n    return Number(r.lastInsertRowid);\n  }\n'''
assert old in s, 'addMessage anchor not found'
s = s.replace(old, new, 1)

old = '''  deleteCustomerChat(waId: string): void {\n    this.db.prepare("DELETE FROM messages WHERE wa_id = ?").run(waId);\n    this.db.prepare("DELETE FROM drafts WHERE wa_id = ?").run(waId);\n    this.db.prepare("DELETE FROM web_sessions WHERE wa_id = ?").run(waId);\n    // Non-order alerts depend on chat context. Once the customer deletes the chat they must not\n    // remain as orphaned "Open chat" tasks for the owner. Order-linked alerts stay for kitchen safety.\n    this.db.prepare("UPDATE alerts SET done = 1 WHERE wa_id = ? AND order_id IS NULL").run(waId);\n    this.db.prepare("UPDATE customers SET profile = '', uncertain_streak = 0 WHERE wa_id = ?").run(waId);\n  }\n'''
new = '''  deleteCustomerChat(waId: string): void {\n    this.db.prepare("DELETE FROM messages WHERE wa_id = ?").run(waId);\n    this.db.prepare("DELETE FROM drafts WHERE wa_id = ?").run(waId);\n    this.db.prepare("DELETE FROM web_sessions WHERE wa_id = ?").run(waId);\n    // Persist a tombstone so later order-ready/thank-you lifecycle events cannot silently recreate\n    // a misleading partial conversation in the owner's Chats list. Orders themselves remain intact.\n    this.kvPut(`owner_chat_deleted:${waId}`, { at: Date.now() });\n    // Non-order alerts depend on chat context. Once the customer deletes the chat they must not\n    // remain as orphaned "Open chat" tasks for the owner. Order-linked alerts stay for kitchen safety.\n    this.db.prepare("UPDATE alerts SET done = 1 WHERE wa_id = ? AND order_id IS NULL").run(waId);\n    this.db.prepare("UPDATE customers SET profile = '', uncertain_streak = 0 WHERE wa_id = ?").run(waId);\n  }\n'''
assert old in s, 'deleteCustomerChat anchor not found'
s = s.replace(old, new, 1)
p.write_text(s)

# ---------- src/server.ts ----------
p = Path('src/server.ts')
s = p.read_text()
old = '''          const customers = store\n            .listCustomers()\n            .map((c) => ({ waId: c.waId, name: c.name, contact: c.contact, last: store.lastMessage(c.waId) ?? null }))\n'''
new = '''          const customers = store\n            .listCustomers()\n            .filter((c) => !store.ownerChatDeleted(c.waId))\n            .map((c) => ({ waId: c.waId, name: c.name, contact: c.contact, last: store.lastMessage(c.waId) ?? null }))\n'''
assert old in s, 'api state customer filter anchor not found'
s = s.replace(old, new, 1)

old = '''          if (m === "GET" && mt[2] === "messages") {\n            const cutoff = store.ownerChatResetAfterMessageId();\n            return send(req, res, 200, { customer: { waId, name: c.name, contact: c.contact }, messages: store.getMessages(waId, 200).filter((x) => x.id > cutoff) });\n          }\n          if (m === "POST" && mt[2] === "reply") {\n            const text = cleanText((await readJson(req)).text, MAX_TEXT);\n'''
new = '''          if (m === "GET" && mt[2] === "messages") {\n            const cutoff = store.ownerChatResetAfterMessageId();\n            const messages = store.ownerChatDeleted(waId) ? [] : store.getMessages(waId, 200).filter((x) => x.id > cutoff);\n            return send(req, res, 200, { customer: { waId, name: c.name, contact: c.contact }, messages });\n          }\n          if (m === "POST" && mt[2] === "reply") {\n            if (store.ownerChatDeleted(waId)) throw new HttpError(410, "This customer deleted the chat. The placed orders are still available in Order history.");\n            const text = cleanText((await readJson(req)).text, MAX_TEXT);\n'''
assert old in s, 'owner messages/reply anchor not found'
s = s.replace(old, new, 1)

old = '''          const note = orderNote(o, o.status, to, s, reason);\n          if (note) store.addMessage(o.waId, "agent", note, now());\n          // After pickup the assistant thanks the customer and asks for feedback, once per order.\n          if (to === "done" && o.status !== "done") store.addMessage(o.waId, "agent", thanksNote(o, s), now());\n'''
new = '''          const note = orderNote(o, o.status, to, s, reason);\n          // A deleted chat stays deleted. Order lifecycle continues in Order history, but lifecycle\n          // notes must not reconstruct a different, partial chat thread for the owner.\n          if (!store.ownerChatDeleted(o.waId)) {\n            if (note) store.addMessage(o.waId, "agent", note, now());\n            // After pickup the assistant thanks the customer and asks for feedback, once per order.\n            if (to === "done" && o.status !== "done") store.addMessage(o.waId, "agent", thanksNote(o, s), now());\n          }\n'''
assert old in s, 'order lifecycle note anchor not found'
s = s.replace(old, new, 1)
p.write_text(s)

# ---------- test/agent.test.ts ----------
p = Path('test/agent.test.ts')
s = p.read_text()
add = r'''\n\ntest("Round 13: pending catering headcount change never routes to cancel a placed order", async () => {\n  const t = setup({ judge: () => ({ cancelPlaced: 0.99 }) });\n  const waId = "+15195550101";\n  t.store.upsertCustomer(waId, "Asha");\n  for (let i = 0; i < 3; i++) {\n    t.store.insertOrder({\n      waId,\n      name: "Asha",\n      items: [{ id: "kheema_fry", name: "Chicken Kheema Fry combo", qty: 1, pack: "single", amt: 18 }],\n      pickup: FRI_6PM,\n      flags: [],\n      status: "cook",\n      notes: "",\n      createdAt: Date.now() + i,\n    });\n  }\n  t.store.putDraft(waId, {\n    items: [{ id: "fry_piece_pulao", name: "Gongura Fry Piece Pulao combo", qty: 20, pack: "single", amt: null }],\n    pickup_local: FRI_6PM,\n    customer_name: "Asha",\n    notes: "",\n    readback_hash: null,\n    stage: "collecting",\n    custom: { request: "Gongura Fry Piece Pulao combo for 20 people", price: 140, approved: true, quote_key: "old-quote" },\n  });\n  const oldAlert = t.store.insertAlert({\n    waId, cust: "Asha", note: "20 people Gongura Fry Piece Pulao needs price quote", orderId: null, createdAt: Date.now(),\n  });\n\n  const r = await t.say("For my new catering request (the Gongura Fry Piece Pulao combo one), please change it to 25 people instead of 20");\n  assert.equal(r.route, "custom_headcount_change");\n  assert.equal(t.llm.prompts.length, 0, "this safety-critical disambiguation is deterministic");\n  assert.equal(t.store.listOrders().length, 3, "no placed order is changed or cancelled");\n  const d = t.store.getDraft(waId)!;\n  assert.equal(d.items[0]!.qty, 25);\n  assert.equal(d.custom!.price, null, "the 20-person quote is invalidated");\n  assert.equal(d.custom!.approved, false);\n  assert.equal(t.store.listAlerts().find((a) => a.id === oldAlert.id)!.done, true, "the stale custom alert is closed");\n  const open = t.store.listAlerts(true);\n  assert.equal(open.length, 1);\n  assert.equal(open[0]!.orderId, null, "the replacement alert is not attached to a real order");\n  assert.match(open[0]!.note, /Custom\\/bulk request updated: 25 people/);\n  assert.match(r.replies[0]!, /No placed order was changed/);\n});\n'''
# Write escaped test as actual TS newlines.
add = add.encode('utf-8').decode('unicode_escape')
s += add
p.write_text(s)

# ---------- test/web.test.ts ----------
p = Path('test/web.test.ts')
s = p.read_text()
old = '''      assert.equal((await call("GET", "/web/history", { token })).status, 401);\n      assert.equal(t.store.listOrders().length, 1);\n    }));\n});\n'''
new = '''      assert.equal((await call("GET", "/web/history", { token })).status, 401);\n      assert.equal(t.store.listOrders().length, 1);\n\n      // Regression: order lifecycle events after deletion must not reconstruct a fake, partial chat.\n      const orderId = t.store.listOrders()[0]!.id;\n      await call("POST", `/api/orders/${orderId}/status`, { token: "secret", body: { status: "ready", confirm: true } });\n      await call("POST", `/api/orders/${orderId}/status`, { token: "secret", body: { status: "done", confirm: true } });\n      assert.equal(t.store.getMessages(wa, 50).length, 0, "ready/thank-you notes do not recreate deleted messages");\n      const owner = await call("GET", "/api/state", { token: "secret" });\n      assert.equal(owner.json.customers.some((c: any) => c.waId === wa), false, "deleted chat stays out of owner Chats");\n      assert.equal(owner.json.orders.some((o: any) => o.waId === wa), true, "order history is preserved");\n      const thread = await call("GET", `/api/customers/${encodeURIComponent(wa)}/messages`, { token: "secret" });\n      assert.deepEqual(thread.json.messages, [], "direct thread lookup is an honest empty state");\n      assert.equal((await call("POST", `/api/customers/${encodeURIComponent(wa)}/reply`, { token: "secret", body: { text: "hello" } })).status, 410);\n    }));\n});\n'''
assert old in s, 'web delete test anchor not found'
s = s.replace(old, new, 1)
p.write_text(s)
